apiVersion: v1
kind: Service
metadata:
  namespace: sonar
  labels:
    app: sonarqube
  name: sonarqube
spec:
  ports:
    - name: sonarqube
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
  type: NodePort
