apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sonar
  name: sonar-extensions
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 16Gi