{'build_type': 3,
 'build_version': {'client_modules': [{'name': 'assetbundle',
                                       'repo': None,
                                       'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                      {'name': 'dataconfig',
                                       'repo': None,
                                       'tag': 'Numeric#prerelease#38491'},
                                      {'name': 'frontend',
                                       'repo': None,
                                       'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                      {'name': 'luascript',
                                       'repo': 'git@git.youle.game:dk/dk-client-group/client-lua.git',
                                       'tag': 'master.191009.01'}],
                   'client_version': 'c-3592',
                   'client_version_id': 3592,
                   'server_modules': [{'name': 'battleserver',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                       'tag': 'prerelease.190921.03'},
                                      {'name': 'dataconfig',
                                       'repo': None,
                                       'tag': 'Numeric#prerelease#38491'},
                                      {'name': 'gameserver',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                       'tag': 'prerelease.190921.03'},
                                      {'name': 'global',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/global.git',
                                       'tag': 'prerelease.190922.02'},
                                      {'name': 'luascript',
                                       'repo': 'git@git.youle.game:dk/dk-client-group/client-lua.git',
                                       'tag': 'master.191009.01'},
                                      {'name': 'notice',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/notice.git',
                                       'tag': 'master.190912.01'},
                                      {'name': 'pipeline-meta',
                                       'repo': 'git@git.youle.game:dk/dk-pipeline.git',
                                       'tag': 'master.190921.03'},
                                      {'name': 'snapshot',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                       'tag': 'prerelease.190921.03'},
                                      {'name': 'vms',
                                       'repo': 'git@git.youle.game:dk/dk-server-group/notice.git',
                                       'tag': 'master.190912.01'}],
                   'server_version': 's-3593',
                   'server_version_id': 3593},
 'deployment': OrderedDict([('bound_store_review_id', None),
                            ('cdn_url', 'https://lwcs2cdn.dashenq.com/hwqd'),
                            ('cluster_id', 120),
                            ('game_id', 1),
                            ('global_url',
                             'https://dlsn-global-qd.dashenq.com:8810'),
                            ('id', 23),
                            ('is_active', True),
                            ('is_store_review', False),
                            ('meta_dir', ''),
                            ('name', 'HWQD'),
                            ('nocdn_url',
                             'https://dlsn-cdn-hw.dashenq.com/hwqd'),
                            ('notice_server_url',
                             'https://dlsn-notice-qd.dashenq.com:8804'),
                            ('vms_server_url',
                             'https://dlsn-vms-qd.dashenq.com:8800'),
                            ('platform_ids', [119]),
                            ('store_review_global_url', None),
                            ('ERROR_REPORT_URL',
                             'https://log-data.topjoy.com/sync_data')]),
 'game_name': 'dk',
 'job_id': 2011,
 'online_version': {'production': {'client_modules': [{'name': 'assetbundle',
                                                       'repo': None,
                                                       'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                                      {'name': 'dataconfig',
                                                       'repo': None,
                                                       'tag': 'Numeric#prerelease#38491'},
                                                      {'name': 'frontend',
                                                       'repo': None,
                                                       'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                                      {'name': 'luascript',
                                                       'repo': 'git@git.youle.game:dk/dk-client-group/client-lua.git',
                                                       'tag': 'prerelease.190921.01'}],
                                   'client_version': 'c-3461',
                                   'client_version_id': 3461,
                                   'server_modules': [{'name': 'battleserver',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                                       'tag': 'prerelease.190921.03'},
                                                      {'name': 'dataconfig',
                                                       'repo': None,
                                                       'tag': 'Numeric#prerelease#38491'},
                                                      {'name': 'gameserver',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                                       'tag': 'prerelease.190921.03'},
                                                      {'name': 'global',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/global.git',
                                                       'tag': 'prerelease.190922.02'},
                                                      {'name': 'luascript',
                                                       'repo': 'git@git.youle.game:dk/dk-client-group/client-lua.git',
                                                       'tag': 'prerelease.190921.01'},
                                                      {'name': 'notice',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/notice.git',
                                                       'tag': 'master.190912.01'},
                                                      {'name': 'pipeline-meta',
                                                       'repo': 'git@git.youle.game:dk/dk-pipeline.git',
                                                       'tag': 'master.190921.03'},
                                                      {'name': 'snapshot',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/dk-server.git',
                                                       'tag': 'prerelease.190921.03'},
                                                      {'name': 'vms',
                                                       'repo': 'git@git.youle.game:dk/dk-server-group/notice.git',
                                                       'tag': 'master.190912.01'}],
                                   'server_version': 's-3462',
                                   'server_version_id': 3462}},
 'release': 'production',
 'target': {'client': {'create_update_package': True,
                       'force_logout': True,
                       'installation_package': {'dk_android': {'full': 1}}},
            'server': {'compatible_client_version': ['c-3592'],
                       'minimal_upgradable_client_version': 'c-3446'}},
 'upgrade_package_info': {'c-3446_c-3592': {'from_module_tag': {'assetbundle': {'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                                                'dataconfig': {'tag': 'Numeric#prerelease#38447'},
                                                                'frontend': {'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                                                'luascript': {'tag': 'prerelease.190920.06'}},
                                            'from_version': 'c-3446',
                                            'from_version_id': 3446,
                                            'to_module_tag': {'assetbundle': {'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                                              'dataconfig': {'tag': 'Numeric#prerelease#38491'},
                                                              'frontend': {'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                                              'luascript': {'tag': 'master.191009.01'}},
                                            'to_version': 'c-3592',
                                            'to_version_id': 3592},
                          'c-3461_c-3592': {'from_module_tag': {'assetbundle': {'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                                                'dataconfig': {'tag': 'Numeric#prerelease#38491'},
                                                                'frontend': {'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                                                'luascript': {'tag': 'prerelease.190921.01'}},
                                            'from_version': 'c-3461',
                                            'from_version_id': 3461,
                                            'to_module_tag': {'assetbundle': {'tag': 'DKClient_prerelease#Assets#WorkAssets#38379'},
                                                              'dataconfig': {'tag': 'Numeric#prerelease#38491'},
                                                              'frontend': {'tag': 'DKClient_prerelease#Assets#Scripts#37581'},
                                                              'luascript': {'tag': 'master.191009.01'}},
                                            'to_version': 'c-3592',
                                            'to_version_id': 3592}},
 'upgrade_paths': [{'id': 2,
                    'name': 'dk_android',
                    'profiles': [{'frontend': 'profile_android.yaml'},
                                 {'assetbundle': 'profile_android.yaml'},
                                 {'dataconfig': 'profile_all.yaml'},
                                 {'luascript': 'profile_all.yaml'}]},
                   {'id': 4,
                    'name': 'dk_ios',
                    'profiles': [{'frontend': 'profile_ios.yaml'},
                                 {'assetbundle': 'profile_ios.yaml'},
                                 {'dataconfig': 'profile_all.yaml'},
                                 {'luascript': 'profile_all.yaml'}]}],
 'walle_url': 'http://127.0.0.1:5000/'}
